### ISSUE TITLE
Move to lab-infrastructure

### ISSUE THREAD

**Issue by enricgalceran** [ethz-asl/lab-infrastructure#1]
To avoid yet another standalone repo.

You should have access to lab-infrastructure now @hitzg

**Comment by hitzg** [comment]
My intention was to make the repo pulic, so that others can contribute / view the code.
But i guess i can also move it to the infrastructure repo.

btw: is there a restriction on the number of public repos we can have?

**Comment by enricgalceran** [comment]
Not sure about maximum number of public repos.

We could create a lab-infrasteucture-public perhaps, I'd also like to make my github tools public.

**Comment by HannesSommer** [comment]
I like the idea of a public infrastructure repository. It could even have the private one as optional submodule. That would allow mixing private and public stuff on a fine grained level.

**Comment by hitzg** [comment]
Ok, should I create one (i.e., rename the one I created?) Or should I move my stuff to the private one for now?

@HannesSommer Wouldn't it be simpler to have the public one as a submodule in the private one?

**Comment by enricgalceran** [comment]
@hitzg I would rename the current one to "lab-infrastructure-private", create a new public one called "lab-infrastructure", and have the public one as submodule in the private one. That way the public name exposed is just "lab-infrastructure", as opposed to the more ugly "lab-infrastructure-public".

Once "lab-infrastructure" (public) is set we can public-to-be contents there.

Sound good @HannesSommer?

**Comment by HannesSommer** [comment]
:+1: for a new public lab-infrastructure (might very well be a renamed student_presentation_calendar)  and the old renamed to lab-infrastructure-private. However I'm not sure which submodule relation is better. I guess it is simpler - at least for the usecase of public code taking secret information out of the private one - if the private one is submodule of the public. On the other hand it is nicer for the public not to have a sub module which not everybody is allowed to fetch.

Hm, I think for me simplicity counts more here and I vote for the first option :). The order is actually not fixed for all time. We can change later if it seems better.

I guess, the private's major value will probably be located in its wiki and issues.

**Comment by HannesSommer** [comment]
If the public contains code possibly automatically accessing private information then pushing to it is as security relevant as the private itself! Maybe we want to limit the write access therefore and be a bit careful with pull requests - at least if they impact such type of code.

**Comment by hitzg** [comment]
Good point. After all it is not very important to make these scripts public... Maybe its simpler if we just keep it private and whenever someone is interested we just grant them access to the private one?

**Comment by enricgalceran** [comment]
In the case of github_archiver, it is a standalone tool, and I'd like to make it public. If lab-infrastructure does not go public I'll move it to one of my personal repos, and import them as a submodule into lab-infrastructure or something like that.

**Comment by HannesSommer** [comment]
Actually I think it is enough to audit the code before it gets updated on servers. Any other way is probably to insecure anyway. And to reduce effort here one could sign tags and move to signed tags only on the servers. I could look into that before setting up automatic updating (it doesn't exist so far). 

Let's not worry to much about future use. All that can be changed. At the moment I don't think there is a problem with putting the scripts in a public lab-infrastructure repository.
In fact the private one should be kept as small as possible anyway because then there is less reason to give wide access. From that point of view it is even a good thing to move the less confidential scripts to a public one.

**Comment by hitzg** [comment]
Ok. That sounds good to me.
So I will:
1. Rename **lab-infrastructure** to **lab-infrastructure-private**
2. Rename **student_presentation_calendar** to **lab-infrastructure**

Objections?

**Comment by HannesSommer** [comment]
No objections from my side :).

**Comment by hitzg** [comment]
Turns out I don't have permission to do 1). Therefore, I also can't do 2).

**Comment by HannesSommer** [comment]
@enricgalceran , fine for you? Do you want to do it? Otherwise I'll do it.

**Comment by enricgalceran** [comment]
Did 1). Update URLs for lab-infrastructure(-private). @HannesSommer @hitzg

**Comment by enricgalceran** [comment]
Also did 2).@HannesSommer @hitzg

**Comment by hitzg** [comment]
Thanks!

**Comment by HannesSommer** [comment]
Great, Thanks!

**Comment by HannesSommer** [comment]
I guess this is done.
